### ISSUE TITLE
Make Dialog box overflow if it extends past the window.

### ISSUE THREAD

**Issue by ebsi-cgoboncan** [etaque/elm-dialog#3]
The bottom of the dialog box is not accessible when the dialog is taller than the window.

**Comment by etaque** [comment]
Would you mind to have a look at how the CSS could be tuned to solve this?

**Comment by ebsi-cgoboncan** [comment]
Which IE browser version are you supporting?

**Comment by etaque** [comment]
10 would be good!
That said, a finely tuned stylesheet isn't my main goal here, it's more about showing how a modal can be architectured in Elm.

Thanks for the effort :)

**Comment by ebsi-cgoboncan** [comment]
How about this?

``` css
.modal {
...
  overflow-x: hidden;
  overflow-y: auto !important;
}
```

This is what bootstrap 3 does.
